theme: jekyll-theme-cayman
title: Mitigating data replication in text-to-audio generative diffusion models through anti-memorization guidance
description: "   "
show_downloads: True
colors:
    gradient_left: "#c972a5"
    gradient_right: "#be0973"

markdown: GFM
